sonar.projectKey=ACEest-main
sonar.projectName=AceTest
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=sqp_eb0e54ec091af13b8229cc3ac10d090245c36909
sonar.exclusions=venv/**,__pycache__/**,*.pyc