apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-app
spec:
  replicas: 1

  selector:
    matchLabels:
      app: aceest

  template:
    metadata:
      labels:
        app: aceest

    spec:
      containers:
      - name: aceest-container
        image: YOUR_DOCKERHUB_USERNAME/aceest:latest

        ports:
        - containerPort: 5000