apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest
      version: canary
  template:
    metadata:
      labels:
        app: aceest
        version: canary
    spec:
      containers:
      - name: aceest
        image: nginx:latest
        ports:
        - containerPort: 80
