apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-recreate
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: aceest
  template:
    metadata:
      labels:
        app: aceest
    spec:
      containers:
      - name: aceest
        image: nginx:latest
        ports:
        - containerPort: 80
