apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-rolling
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: aceest
  template:
    metadata:
      labels:
        app: aceest
    spec:
      containers:
      - name: aceest
        image: nginx:latest
        ports:
        - containerPort: 80
